SELECT 
	CONVERT(CONCAT((LEFT(Kunden.Kundennummer, 5)),(RIGHT(Kundenkontakt.Nummer, 2))), SQL_CHAR) AS [ID_NR], 
	CONCAT((CONCAT((CONCAT(INSERT(Kunden.Kundennummer, 6, 5, SPACE(1)),(UCASE(Kunden.Kurzbezeichnung)))), CHAR(44))), (Kundenkontakt.Name)) AS [Filename], 
	Kundenkontakt.Name AS [FamilyName], 
	LEFT(Kundenkontakt.Name, 0) AS [GivenName], 
	LEFT(Kundenkontakt.Name, 0) AS [Title], 
	LEFT(Kundenkontakt.Name, 0) AS [NamePrefix], 
	LEFT(Kundenkontakt.Name, 0) AS [NameSuffix], 
	LEFT(Kundenkontakt.Name, 0) AS [Nickname], 
	LEFT(Kundenkontakt.Geburtstag, 0) AS [Birthdate], 
	RIGHT(CONVERT(Kunden.Timestamp_Datum, SQL_CHAR), 2) AS [Day], 
	SUBSTRING(CONVERT(Kunden.Timestamp_Datum, SQL_CHAR), 6, 2) AS [Month], 
	LEFT(CONVERT(Kunden.Timestamp_Datum, SQL_CHAR), 4) AS [Year], 
	Kunden.Strasse AS [Street], 
	Kunden.Laendercode AS [State], 
	Kunden.Postleitzahl AS [PostalCode], 
	Kunden.Ort AS [City], 
	LEFT(Kunden.Laendercode, 0) AS [Country], 
	Kundenkontakt.Telefon AS [Tel], 
	LEFT(Kundenkontakt.Telefon, 0) AS [TelHome], 
	Kunden.Telefon AS [TelWork], 
	Kundenkontakt.Handy AS [TelCell], 
	LEFT(Kundenkontakt.Autotelefon, 0) AS [TelCellHome], 
	Kundenkontakt.Autotelefon AS [TelCellWork], 
	Kundenkontakt.Telefax AS [TelFax], 
	LEFT(Kundenkontakt.Telefax, 0) AS [TelFaxHome], 
	Kunden.Telefax AS [TelFaxWork], 
	Kundenkontakt.E_Mail AS [Email], 
	LEFT(Kundenkontakt.E_Mail, 0) AS [EmailHome], 
	Kunden.E_Mail AS [EmailWork], 
	Kunden.Homepage AS [Url], 
	LEFT(Kunden.Homepage, 0) AS [UrlHome], 
	LEFT(Kunden.Homepage, 0) AS [UrlWork], 
	CONCAT(Kunden.Name1,CONCAT(SPACE(1), Kunden.Name2)) AS [Org], 
	Kundenkontakt.Abteilung AS [Role], 
	Kunden.Memo_Anker_NurText AS [MEMO], 
	Kundenkontakt.Infofeld AS [Note], 
	LEFT(Kunden.Strasse, 0) AS [StreetHome], 
	LEFT(Kunden.Laendercode, 0) AS [StateHome], 
	LEFT(Kunden.Kundennummer, 5) AS [PostalCodeHome], 
	LEFT(Kunden.Ort, 0) AS [CityHome], 
	LEFT(Kunden.Laendercode, 0) AS [CountryHome], 
	LEFT(Kunden.Strasse, 0) AS [StreetWork], 
	LEFT(Kunden.Laendercode, 0) AS [StateWork], 
	LEFT(Kunden.Postleitzahl, 0) AS [PostalCodeWork], 
	LEFT(Kunden.Ort, 0) AS [CityWork], 
	LEFT(Kunden.Laendercode, 0) AS [CountryWork] 
FROM 
	Kunden AS Kunden, 
	Kundenkontakt AS Kundenkontakt 
WHERE 
		 Kundenkontakt.Kundennummer = Kunden.Kundennummer 
	AND (Kunden.Statuskennzeichen <> 'Ja') 
	AND (Kundenkontakt.Satzart = 'A') 
ORDER BY 
	Kunden.Kundennummer, Kundenkontakt.Nummer
