//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.Common.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Axel")]
        public string ATAPI_Line {
            get {
                return ((string)(this["ATAPI_Line"]));
            }
            set {
                this["ATAPI_Line"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AU")]
        public string UserInSage {
            get {
                return ((string)(this["UserInSage"]));
            }
            set {
                this["UserInSage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\Cpm-dc\\sage new classic\\2014\\EXE\\CL.EXE")]
        public string Sage_ExePath {
            get {
                return ((string)(this["Sage_ExePath"]));
            }
            set {
                this["Sage_ExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\cpm-dc\\sage_ncl\\catalist\\kundenkataloge\\")]
        public string CatalogPath {
            get {
                return ((string)(this["CatalogPath"]));
            }
            set {
                this["CatalogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\cpm-dc\\sage_ncl\\catalist\\template\\catalogtemplate.docx")]
        public string CatalogTemplateFilePath {
            get {
                return ((string)(this["CatalogTemplateFilePath"]));
            }
            set {
                this["CatalogTemplateFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,19")]
        public string TaxRate {
            get {
                return ((string)(this["TaxRate"]));
            }
            set {
                this["TaxRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\cpm-dc\\sage_ncl\\catalist\\graphics\\")]
        public string PicturePath {
            get {
                return ((string)(this["PicturePath"]));
            }
            set {
                this["PicturePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\cpm-dc\\sage_ncl\\catalist\\graphics\\manufacturer\\")]
        public string ManufacturerPicturePath {
            get {
                return ((string)(this["ManufacturerPicturePath"]));
            }
            set {
                this["ManufacturerPicturePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\cpm-dc\\sage_ncl\\catalist\\graphics\\productpics\\")]
        public string ProductPicturePath {
            get {
                return ((string)(this["ProductPicturePath"]));
            }
            set {
                this["ProductPicturePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\Cpm-dc\\sage_ncl\\catalist\\offers\\")]
        public string OfferFilePath {
            get {
                return ((string)(this["OfferFilePath"]));
            }
            set {
                this["OfferFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int CmdPanelVisibleTime {
            get {
                return ((int)(this["CmdPanelVisibleTime"]));
            }
            set {
                this["CmdPanelVisibleTime"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.bing.com/maps/default.aspx?where1=")]
        public string BingMapsUrl {
            get {
                return ((string)(this["BingMapsUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.102")]
        public string SmtpServer {
            get {
                return ((string)(this["SmtpServer"]));
            }
            set {
                this["SmtpServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public string SmtpPort {
            get {
                return ((string)(this["SmtpPort"]));
            }
            set {
                this["SmtpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a.ullrich@cut-print.de")]
        public string SenderEmailAddress {
            get {
                return ((string)(this["SenderEmailAddress"]));
            }
            set {
                this["SenderEmailAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36800")]
        public string SenderPW {
            get {
                return ((string)(this["SenderPW"]));
            }
            set {
                this["SenderPW"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\david\\david\\archive\\user\\")]
        public string DavidArchivePath {
            get {
                return ((string)(this["DavidArchivePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\Cpm-dc\\sage_ncl\\catalist\\dateilinks\\")]
        public string LinkedFilesPath {
            get {
                return ((string)(this["LinkedFilesPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\cpm-dc\\sage_ncl\\catalist\\template\\")]
        public string TemplatePath {
            get {
                return ((string)(this["TemplatePath"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Signature {
            get {
                return ((string)(this["Signature"]));
            }
            set {
                this["Signature"] = value;
            }
        }
    }
}
